# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2

registries:
  public-nuget:
    type: nuget-feed
    url: https://api.nuget.org/v3/index.json

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 15

  updates:
  - package-ecosystem: nuget
    directory: "/"
    registries:
      - public-nuget
    schedule:
      interval: daily
    open-pull-requests-limit: 15
    groups:
      Aspire:
        patterns:
          - "Aspire.*"
          - "Microsoft.Extensions.ServiceDiscovery.*"
      AspNetCore:
        patterns:
          - "Microsoft.AspNetCore.*"
      EntityFrameworkCore:
        patterns:
          - "Microsoft.EntityFrameworkCore*"
      MicrosoftExtensions:
        patterns:
          - "Microsoft.Extensions.*"
          - "Microsoft.Bcl.*"
      OpenTelemetry:
        patterns:
          - "OpenTelemetry.*"
      MicrosoftTest:
        patterns:
          - "Microsoft.NET.Test.*"
      xunit:
        patterns:
          - "xunit*"



