name: Render PlantUML

on: 
  push:
    paths:
      - '**/*.puml'
      - '.github/workflows/render-plantuml.yml'
  pull_request:
    paths:
      - '**/*.puml'
      - '.github/workflows/render-plantuml.yml'

jobs:
  render:
    runs-on: ubuntu-latest

    env:
      OUTPUT_DIR: "documentation/puml_rendered"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Start PlantUML Server
        run: |
          docker run -d --name plantuml-server -p 8080:8080 plantuml/plantuml-server:jetty

      - name: Render PUML files to SVG
        run: |
          mkdir -p ${{ env.OUTPUT_DIR }}
          for file in $(find . -name '*.puml'); do
            filename=$(basename -- "$file")
            curl -o ${{ env.OUTPUT_DIR }}/${filename%.puml}.svg "http://localhost:8080/svg/$file"
          done

      - name: Configure git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Commit and push changes
        run: |
          git add ${{ env.OUTPUT_DIR }}
          git commit -m "Rendered SVGs from PUML files"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}