name: Render PlantUML

on: 
  push:
    paths:
      - '**/*.puml'
      - '.github/workflows/render-plantuml.yml'
  pull_request:
    paths:
      - '**/*.puml'
      - '.github/workflows/render-plantuml.yml'

jobs:
  render:
    runs-on: ubuntu-latest
    
    container:
      image: plantuml/plantuml:latest
      options: --entrypoint /bin/sh

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set output path
      id: vars
      run: echo "::set-output name=output_path::${{ github.workspace }}/output"

    - name: Create output directory
      run: mkdir -p ${{ steps.vars.outputs.output_path }}

    - name: Render PUML files to SVG
      run: |
        # Find all .puml files and convert them to .svg
        find . -name "*.puml" -print0 | while IFS= read -r -d '' file; do
          svg_file="${{ steps.vars.outputs.output_path }}/${file%.puml}.svg"
          java -jar /opt/plantuml.jar -tsvg "$file" -o "${{ steps.vars.outputs.output_path }}"
        done

    - name: Commit and push changes
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: 'Render PUML files to SVG'
        file_pattern: '${{ steps.vars.outputs.output_path }}/**/*.svg'
        branch: ${{ github.ref }}
